language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t sks999us/multi-test -f ./client/Dockerfile.dev ./client
script:
  - docker run -e CI=true  sks/multi-test npm test

after_scuess:
  - docker build -t sks999us/multi-client ./client
  - docker build -t sks999us/multi-nginx ./nginx
  - docker build -t sks999us/multi-server ./server
  - docker build -t sks999us/multi-worker ./worker

# login to docker hub
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  ###
  - docker push sks999us/multi-client
  - docker push sks999us/multi-nginx
  - docker push sks999us/multi-server
  - docker push sks999us/multi-worker

