language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t sks999us/multi-test -f ./client/Dockerfile.dev ./client
script:
  - docker run -e CI=true  sks999us/multi-test npm test

after_scuess:
  - docker build -t sks999us/multi-client ./client
  - docker build -t sks999us/multi-nginx ./nginx
  - docker build -t sks999us/multi-server ./server
  - docker build -t sks999us/multi-worker ./worker

# login to docker hub
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  ###
  - docker push sks999us/multi-client
  - docker push sks999us/multi-nginx
  - docker push sks999us/multi-server
  - docker push sks999us/multi-worker

deploy:
  provider: elasticbeanstalk
  region: us-east-1
  app: cs-multi-docker
  env: CsMultiDocker-env
  bucket_name: elasticbeanstalk-us-east-1-478389293650
  bbucket_path: docker_multi
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY  
